### ISSUE TITLE
46 params vs SMPL 72 params

### ISSUE THREAD

**Issue by jez-moxmo** [MarilynKeller/SKEL#1]
Hi, fantastic work on this project. I am still in the process of reading the article but looking at the code, do the 46 parameters represent linked positions? I.e., index 0-3 is orientation for joint a, and index 3-5 is orientation for joint b? Whereas smpl is just 23x3. 

*edit meant index [0, 1, 2] , [2, 3, 4]... etc.

**Comment by MarilynKeller** [comment]
Hi, I am not sure what you mean by "linked position".

SMPL has 24*3=72 pose parameters, three angle per joints. The first joint is in the pelvis and controls the global orientation of the model.
SKEL has also 24 joints but they are placed differently, and some of those joints like the knee and elbow have only 1 degree of freedom, hence only 46 pose parameters.

You can see the list of SKEL's 46 DOF with their name [here](https://github.com/MarilynKeller/SKEL/blob/4a606675af79f50e6820f5a9b0964fd55c02f538/skel/kin_skel.py#L29)

And you can observe the effect of each of those pose parameters with this script:
```python examples/skel_poses.py --gender male``` as explained [here](https://github.com/MarilynKeller/SKEL/blob/master/README.md).

I hope this clarifies.

**Comment by jez-moxmo** [comment]
> Hi, I am not sure what you mean by "linked position".
> 
> SMPL has 24*3=72 pose parameters, three angle per joints. The first joint is in the pelvis and controls the global orientation of the model. SKEL has also 24 joints but they are placed differently, and some of those joints like the knee and elbow have only 1 degree of freedom, hence only 46 pose parameters.
> 
> You can see the list of SKEL's 46 DOF with their name [here](https://github.com/MarilynKeller/SKEL/blob/4a606675af79f50e6820f5a9b0964fd55c02f538/skel/kin_skel.py#L29)
> 
> And you can observe the effect of each of those pose parameters with this script: `python examples/skel_poses.py --gender male` as explained [here](https://github.com/MarilynKeller/SKEL/blob/master/README.md).
> 
> I hope this clarifies.

thanks for the clarification. I had a bit more of a read of the article. It looks like a good format for compression. So they take in Euler angles and several joints only have 1 dof as many only move in one relative angle. I'm new to the SMPL eco-system. the SMPL 72 betas are just 24x3dof Euler in radians? So seems like conversion should be easy then. Thank you kindly. 

It says you're still a Ph.D student? Is this github a synthesis of your thesis? Has it been submitted and available to read? I'm working on many similar concepts but around motor primtiives.

**Comment by MarilynKeller** [comment]
You got it, to be precise, the SMPL pose vector (thetas in R^72) are rodrigues angle in radian.
The conversion to the SKEL pose parameters (q in R^46, euler angles) is actually not trivial as the joints locations are different from SMPL (see the two different kinematic trees in the paper).

I am in the end of my PhD but still working on my thesis, so it is not yet submitted. Feel free to drop me an email, I would be curious to know more about what you and your lab are working on. I haven't heard of "motor primitives" before. ([here are my contacts](https://marilynkeller.github.io/))
