### ISSUE TITLE
Error on .osim import

### ISSUE THREAD

**Issue by amaliacontiero** [MarilynKeller/SKEL#10]
Hello, first of all thank you for your amazing work on combining SMPL and Opensim models! I'm still in the process of reading the publication. I tried to check out the BSM.osim model both in OpenSim and OpenSim Creator, but I encountered an import issue.

OpenSim:
![image](https://github.com/MarilynKeller/SKEL/assets/29499343/0afb5f4d-0301-438d-81a3-be35ec413f37)

OpenSim Creator: 
![image](https://github.com/MarilynKeller/SKEL/assets/29499343/2c9ca8f9-cf64-48fd-888b-a5be2a8b037b)

I downloaded the model from the website (skel_models_v1 zip). Does this import fine for anyone else?
I extracted the zip contents as they are from the master folder, and imported bsm.osim with same file structure, although I think it shouldn't matter.

My interest in this is because I want to use it with OpenSense for visualizing IK from IMUs. Rajagopal and "Thoracolumbar spine and rib cage" osim models didn't work well for my specific use case. Are the joint angles predicted in .ik similar to SMPL?

**Comment by MarilynKeller** [comment]
Hi,

The current BSM.osim model is only compatible with nimblephysics for now.

We are tracking this compatibility issue here:
- https://github.com/MarilynKeller/SMPL2AddBiomechanics/issues/5
- https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=17422&p=48432
