### ISSUE TITLE
RuntimeError: This version of skel.pkl is deprecated, please download the latest version from https://skel.is.tue.mpg.de/download.html

### ISSUE THREAD

**Issue by LongDan15** [MarilynKeller/SKEL#13]
(skel) ➜  SKEL git:(master) ✗ python examples/skel_rigging.py --gender female  
Traceback (most recent call last):
  File "examples/skel_rigging.py", line 22, in <module>
    skel_model = SKEL(gender)
  File "/home/holmes/longdan/SKEL/skel/skel_model.py", line 96, in __init__
    raise RuntimeError('This version of skel.pkl is deprecated, please download the latest version from https://skel.is.tue.mpg.de/download.html')
RuntimeError: This version of skel.pkl is deprecated, please download the latest version from https://skel.is.tue.mpg.de/download.html
(skel) ➜  SKEL git:(master) ✗ python examples/skel_kintree.py --gender female
Traceback (most recent call last):
  File "examples/skel_kintree.py", line 20, in <module>
    skel_model = SKEL(gender)
  File "/home/holmes/longdan/SKEL/skel/skel_model.py", line 96, in __init__
    raise RuntimeError('This version of skel.pkl is deprecated, please download the latest version from https://skel.is.tue.mpg.de/download.html')
RuntimeError: This version of skel.pkl is deprecated, please download the latest version from https://skel.is.tue.mpg.de/download.html
(skel) ➜  SKEL git:(master) ✗

**Comment by MarilynKeller** [comment]
As the error says, please re-download the latest version of the skel model folder at: https://skel.is.tue.mpg.de/download.html

**Comment by MarilynKeller** [comment]
I just fixed a bug in the .pkl. Please redownload them if you already did.
