### ISSUE TITLE
Spine misalignment

### ISSUE THREAD

**Issue by Hydran00** [MarilynKeller/SKEL#16]
Hi, thank you for your impressive work! 

I noticed that there seems to be a misalignment in the backbone between two vertebrae. This can also be seen when every parameter is set to zero (betas, body pose and transl). The artifact is well visible in the [kinematic tree image](https://github.com/MarilynKeller/SKEL/blob/master/assets/skel_kin_tree.png) over the 11th joint. Do you have any ideas about why is it there?

**Comment by MarilynKeller** [comment]
Hi, indeed, I'm aware of the issue. It comes from the template skeleton mesh `skel_model.skel_template_v`which has the thorax is a bit tilted. I didn't have time to fix it so far. But you can fix it by isolating and rectifying the thorax in the template skeleton mesh.

**Comment by Hydran00** [comment]
Ok, thank you!

**Comment by Hydran00** [comment]
For now, I found a little workaround, which is adding a small offset to the thorax when the alignment between thorax and lumbar is done. I added an offset on the X axis after this [line](https://github.com/MarilynKeller/SKEL/blob/master/skel/skel_model.py#L634)  in `skel/skel_model.py`.

I just wrote
```
 bone_vect[:,12][0][0] -= 0.01
```

The result is this
![result](https://github.com/user-attachments/assets/2787cfe7-f782-4141-858a-7e90250c919e)
