### ISSUE TITLE
Generation of Skeletons for infants/kids

### ISSUE THREAD

**Issue by nshreyasvi** [MarilynKeller/SKEL#17]
Hello,
I was trying to run SKEL for SMPL meshes that were extracted for children and infants and would like to know if there is a way to optimize the steps to get accurate joint locations for them? I tried with OSSO and was not able to get a good joint location.

**Comment by MarilynKeller** [comment]
Hi, if you just need the anatomical joints locations, you can directly regress them from your SMPL meshes by running:
```
# smpl_mesh_verts : vertices of your SMPL mesh
# J : regressed anatomical joint locations
skel_model = SKEL(gender)
J = torch.einsum('bik,ji->bjk', [smpl_mesh_verts, skel_model.J_regressor_osim])
```

If you need the bone orientations too then directly fitting SKEL to your SMPL would be the way to go.

**Comment by nshreyasvi** [comment]
Hello, Thank you so much for the information. So, I have generated SMPL .obj files. I was unsure how can I convert these SMPL obj files for individual frames into a SMPL sequence? Does the `merge_output.py` script inside the transfer model generates SMPL sequence file? 

I tried to run align SKEL to a SMPL mesh script to my .pkl SMPL output that I generated. But I am getting the error:
```
KeyError: 'global_orient_axis_angle'
```
If I run it on the examples provided it seems to be working fine.
I wanted to know if there is a difference between the SMPL .pkl files generated from SMPLify-x library compared to the ones that are used in the examples?

**Comment by MarilynKeller** [comment]
I think you are on the right track, you just need to add support for your pkl dictionary in the `load_smpl_seq` function in SKEL/skel/alignment/utils.py to be able to load the SMPL pkl you got. 

Basically the issue is that everyone tends to store the SMPL parameters with different key names. So I only support some names.

Which are the keys present in the .pkl you got ? You can check with:
```
data_dict = pickle.load(open(your_pkl, 'rb'))
print(data_dict.items())
```

You then need to modify the `load_smpl_seq` function to return a dictionary with the following keys:

https://github.com/MarilynKeller/SKEL/blob/832f9a589215c934b4fadf1b5d03f1dab5ef7999/skel/alignment/utils.py#L94C1-L99C46
```
    out_dict['trans'] = data_fixed['trans'] # Fx3 matrix
    out_dict['poses'] = data_fixed['poses'] # Fx72
    out_dict['betas'] = data_fixed['betas'] # Fx10
    out_dict['gender'] = data_fixed['gender'] # ('male' or 'female')
```

Where F is the number of frames.
    Look at the shape of what you get in your pkl to build this output dictionnary

**Comment by nshreyasvi** [comment]
Hello,
Thank you for the quick response. I checked the keys for the .pkl file and they are as follows:
```
dict_keys(['transl', 'global_orient', 'body_pose', 'betas', 'vertices', 'joints', 'full_pose', 'v_shaped', 'faces'])
```
I was a bit unsure on whether I should change the out_dict variable or the data_fixed variable?
Also, do `poses` mean `body_pose` and `transl` mean `trans`?

**Comment by MarilynKeller** [comment]
Alright, thanks for sharing the output

So you have:
data_in = dict_keys(['transl', 'global_orient', 'body_pose', 'betas', 'vertices', 'joints', 'full_pose', 'v_shaped', 'faces'])

And you need:
out_dict['trans'] = data_fixed['trans'] # Fx3 matrix
    out_dict['poses'] = data_fixed['poses'] # Fx72
    out_dict['betas'] = data_fixed['betas'] # Fx10
    out_dict['gender'] = data_fixed['gender'] # ('male' or 'female')
    
   So this should work:
   out_dict['trans'] = data_in['transl']
   out_dict['poses'] = data_in['full_pose']
   out_dict['betas'] = data_in['betas']
   out_dict['gender'] = `male` #( or `female`)

**Comment by nshreyasvi** [comment]
Hello, 
Thank you, I changed the variable names but I am currently getting the following error:
```
Traceback (most recent call last):
  File "examples/align_to_SMPL_frame.py", line 53, in <module>
    skel_seq = skel_fitter.run_fit(smpl_data['trans'], 
  File "/home/scai/Downloads/Shrey/SKEL/skel/alignment/aligner.py", line 83, in run_fit
    body_params = self._init_params(betas_in, poses_in, trans_in, skel_data_init)
  File "/home/scai/Downloads/Shrey/SKEL/skel/alignment/aligner.py", line 154, in _init_params
    poses_skel[:, :3] = poses_smpl[:, :3] # Global orient are similar between SMPL and SKEL, so init with SMPL angles
RuntimeError: expand(torch.cuda.FloatTensor{[3, 3, 3]}, size=[1, 3]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)
```

**Comment by MarilynKeller** [comment]
Could you print the shape of each of these tensors  after you initialized them?

out_dict['trans'] 
out_dict['poses'] 
out_dict['betas']

**Comment by nshreyasvi** [comment]
Hello,
The shapes are as follows:
```
out_dict['trans'] = None
out_dict['poses'].shape or out_dict['full_pose'].shape=torch.Size([1, 24, 3, 3])
out_dict['betas'].shape = torch.Size([1, 10])
```

**Comment by nshreyasvi** [comment]
Hello,
Sorry for the delays in response. I checked the shape of each of the parameters in the SMPL model and they have the following shape:
```
transl = None
global_orient = torch.Size([1, 1, 3, 3])
body_pose = torch.Size([1, 23, 3, 3])
betas = torch.Size([1, 10])
vertices = torch.Size([1, 6890, 3])
joints = torch.Size([1, 45, 3])
full_pose = torch.Size([1, 24, 3, 3])
v_shaped = None
faces = (13776, 3)
```
I see that the `beta` key is available in the correct shape but I could not find anything which was of the shape of `theta` (1X72).
I believe that `body_pose` and `full_pose` seems to have the first 3 dimensions correct (1X24X3) but it seems to have an extra dimension.

I wanted to know if there is a way I can use these keys to generate the theta and pose parameters as they should be transferable? I can then write a small function to convert the generated SMPL model into the format used by SKEL so that it converts them in the correct format.
I also tested out the SKEL model by just reshaping the `full_body` and `body_pose` parameters but it seems to twist the SMPL bodies completely. But the SKEL model seems to work then.
I think that the issue is in conversion of the SMPL keys into the keys that can be taken as input here. If there is any resources you could refer me to, that would be great. I have attached the pkl files for the SMPL models I am using along with this message as well. 

[
[proband_gen_1.zip](https://github.com/user-attachments/files/16981401/proband_gen_1.zip)
](url)

Thank you again so much for your time and consideration.

Best,
Shreyasvi

**Comment by MarilynKeller** [comment]
Hi, so you are close. So SMPL parameters are expressed in Nj Rodrigues angles (3 parameters), where Nj=24 is the number of joints of SMPL. What you have is Nj rotation matrices.  Two options (option 2 might be better)

Option 1) So you would "just" need to transform each of these rotation matrix to the rodrigues angle representation. You can do that using opencv
```
$pip install opencv-python
$ python
> poses_params = np.zeros((F,24,3))
> poses_params[f,i] = cv2.Rodrigues(pose[f,i]) where f in a frame (you only have one), and i the joint (from 0 to 23). 

Option 2)
I am not sure in the first place why transfer_models return you matrices and not pose parameters. I checked in their code and you could just modify it to skip the transformation of the pose parameter to matrices:

Edit the transfer_model code here https://github.com/vchoutas/smplx/blob/1265df7ba545e8b00f72e7c557c766e15c71632f/transfer_model/transfer_model.py#L382
to  :
```
for key, var in var_dict.items():
            # Simply pass the variable
            param_dict[key] = var
```
And rerun the transfer. The output dictionary should have directly the proper pose and orient fields.

Good luck!

**Comment by nshreyasvi** [comment]
Hello, I changed the code as per the suggestion, but I am getting the following error in smplx:
```
  File "/home/shrey/smplx/smplx/body_models.py", line 479, in forward
    [global_orient.reshape(-1, 1, 3, 3),
RuntimeError: shape '[-1, 1, 3, 3]' is invalid for input of size 3
```

Could you let me know how can I resolve it so that the format tends to be the same for the output or if I should use any other specific conversion script?

**Comment by nshreyasvi** [comment]
Hello, I was able to solve the issue by using the same HMR output format used [here](https://github.com/MarilynKeller/HIT/issues/2). I further changed line 64 in `skel/alignment/utils.py` and changed the values of `global_orient_axis_angle` and `body_pose_axis_angle` to `global_orient` and `body_pose`. It seems to solve the issue.
