### ISSUE TITLE
Missing Pose Limitation

### ISSUE THREAD

**Issue by IsshikiHugh** [MarilynKeller/SKEL#19]
Hi! Thanks for your great work! I noticed that you have provided a joint rotation limitation configuration here:

https://github.com/MarilynKeller/SKEL/blob/832f9a589215c934b4fadf1b5d03f1dab5ef7999/skel/kin_skel.py#L78-L122

I am very curious about these limitation but I noticed that not all 46 rotation components are listed here. Specifically, these pose_limits are missing:

```py
id = [3, 4, 5, 10, 11, 12, 29, 31, 39, 40, 41]
```

or

```py
name = [
    'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r',
    'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l',
    'shoulder_r_x', 'shoulder_r_z', 'shoulder_l_x', 'shoulder_l_y', 'shoulder_l_z',
]
```

Have you ever measured these limitation? If not, could you please give me some advices on how to calculate a reasonable range? 🥺 (I think the rest is easy but **shoulder's limitation** is a little bit annoying since it is coupled with scapula's rotation.)

🙏 Thank you very much!

**Comment by MarilynKeller** [comment]
Hi, 

well you are right this is not trivial, it's exactly why I could not provide them ^^'.

Ideally, this angle range would have to be measured somehow from fits to various subjects.

An alternative to get this range is to look into our biomechanical model bsm.osim (which is an XML file). There, we have ranges of angles for the humerus and scapula inherited from the shoulder paper of Ajay Seth. I don't remember which field contains the range but chatgpt could help you to find it. This might help for the humerus but for the scapula I don't really have a solution. As far as I know it's an open problem. And it's especially tricky as it depends on the scapula paramétrisation, which tends to vary across implementations.

If you want to check, you can find bsm.osim in the folder containing the SKEL pickles.
Note that in any case, these angle values will still need to be adapted, as the zero pose of SKEL is different from the zero pose of BSM. SKEL is in t-pose while BSM stand straight with the arms along the body, so there is a 45° difference between the humerus elevation angles.

**Comment by IsshikiHugh** [comment]
Thank you very much! I will have a try!
