### ISSUE TITLE
fit to totalcapture smpl sequence

### ISSUE THREAD

**Issue by 2382752230** [MarilynKeller/SKEL#22]
Hi,I saw in the supplementary materials of the paper that it was mentioned to fit skel into the smpl sequence of totalcapture dataset, I would like to know what the effect is? My fit is not good.

**Comment by MarilynKeller** [comment]
We just fit SKEL to a couple of meshes from the TotalCapture dataset for demonstration, not the whole capture. What fitting issues do you encounter?
