### ISSUE TITLE
Turning off Display

### ISSUE THREAD

**Issue by nshreyasvi** [MarilynKeller/SKEL#23]
Hello, I was trying to run the scripts and wanted to disable the meshviewer but was not sure how can i do so?

**Comment by MarilynKeller** [comment]
Hi, could you point to the script in question?

**Comment by nshreyasvi** [comment]
Hello, I believe it would be the script `examples/align_to_smpl_frame.py` or `examples/align_to_smpl_seq.py` which both point to `skel/alignment/aligner.py`. I was not sure where can I change the code so that when I run the `align_to_smpl_frame.py` or the other script, I don't get the meshviewer but the system runs windowless.

**Comment by MarilynKeller** [comment]
You can try to run DISABLE_VIEWER=True in your bash before running the script

**Comment by nshreyasvi** [comment]
Hello, Thank you. I tried to run `DISABLE_VIEWER=1` before running the command.  However, i did not get the print command that was listed there. Also, I was using wsl (ubuntu 22.04) where once the skeleton matching finishes, it just pauses as it expects the output windows to be closed I think because of which the program is stuck.
