### ISSUE TITLE
 Issue with numpy.AxisError in align_to_SMPL.py

### ISSUE THREAD

**Issue by hwy1992129** [MarilynKeller/SKEL#5]
Hello, thanks for great work.
I am window user. nimblephysics doesn't work with me right now, so I am testing the code without Aitviewer.
I encountered error when running the example, `python examples/align_to_SMPL.py /path/to/AMASS/CMU/01/01_01_poses.npz -F` 

```
Traceback (most recent call last):
    skel_seq = skel_fitter.fit(smpl_seq['trans'],
  File "E:\skel\SKEL-master\skel\alignment\aligner.py", line 175, in fit
    betas_in = betas_in.repeat(poses_in.shape[0], 1)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
```

**Comment by MarilynKeller** [comment]
Hi, I just pushed a fix, it should be solved now.

**Comment by MarilynKeller** [comment]
Note that if you are using windows, you will also have to comment out all the psbody.mesh visualizations as it is not supported under windows. Besides this the optimization should work.

**Comment by hwy1992129** [comment]
> Note that if you are using windows, you will also have to comment out all the psbody.mesh visualizations as it is not supported under windows. Besides this the optimization should work.

Thanks, I know how to make psbody work in window. However, the only problem it is nimblephysics... Therefore, I have to run the demo in Ubuntu....

**Comment by MarilynKeller** [comment]
Nice to hear that you could make it work on windows.
For SKEL you should not need nimblephysics. It is only requested to load the bsm.osim model.
