### ISSUE TITLE
Error in fit2joints

### ISSUE THREAD

**Issue by markus-albis** [MarilynKeller/SKEL#8]
When i try to run fit2joints I get the following error:
File "..\skel\examples\fit2joints.py", line 15, in <module>
    from psbody.mesh import Mesh, MeshViewer
ModuleNotFoundError: No module named 'psbody

**Comment by MarilynKeller** [comment]
You need to install the MPI mesh package.

```
pip install -U pip 
pip install git+https://github.com/MPI-IS/mesh.git
```

**Comment by markus-albis** [comment]
Does not work:   ERROR: Failed building wheel for psbody-mesh
When I look in the repo https://github.com/MPI-IS/mesh.git , I see that the package has a dependency on Boost and is not supported on Windows (out-dated ?)

**Comment by MarilynKeller** [comment]
The mpi mesh package is not supported on Windows. 
In this repository, only the visualization of the fitting process uses the psbody.mesh package, so an option is to comment out the lines using it. The optimization itself will still work.
If you need to visualize the optimization, you should then use another library to display the meshes.

**Comment by markus-albis** [comment]
Thanks for the suggestion. That's the route I will take.............. .  I will make a trial with [Trimesh](https://github.com/mikedh/trimesh/tree/main)

**Comment by MarilynKeller** [comment]
The reason I use the MPI mesh package is that it is easy to update the display window with the current mesh every step of the optimization. An alternative would be Trimesh and pyrender to render the mesh every step and save the rendered image.
