### ISSUE TITLE
Does the skeleton have clavicles...?

### ISSUE THREAD

**Issue by hwy1992129** [MarilynKeller/SKEL#9]
I suddenly found clavicles are missed.... I checked your paper. The figures in image show no clavicles, either......

**Comment by MarilynKeller** [comment]
Hi, indeed our model does not have clavicle, as the rigging is a specific challenge that we did not adress. Indeed, the clavicle should stay attached to the sternum and scapula, which can be enforced by constraints but not easily with explicit rigging like SKEL does.
